config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  root 'tasks#index'
  post '/tasks/:id/toggle' => 'tasks#toggle'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :title,
    presence: { message: 'タイトルを入力してください！'},
    length: {minimum: 5, message: '5文字以上で入力してください'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
     @tasks = Task.all
    end
    
    def new
       @task = Task.new 
    end
    
    def create
        @task = Task.new(task_params)
        
        if @task.save
            redirect_to root_path
        else
            render 'new'
        end
    end
    
    def edit
        @task = Task.find(params[:id])
    end
    
    def update
        @task = Task.find(params[:id])
        if @task.update(task_params)
            redirect_to root_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to root_path
    end
    
    def toggle
        
        head :no_content
        @task = Task.find(params[:id])
        @task.done = !@task.done
        @task.save
    end
    
    private
        def task_params
            params[:task].permit(:title)
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>編集画面</h1>
<%= form_for @task do |f| %>
    <p>
        <%= f.label :title %> <br>
        <%= f.text_field :title %>
        <% if @task.errors.any? %>
            <%= @task.errors.messages[:title][0] %>
        <% end %>
        
    </p>
    <p>
        <%= f.submit %>
    </p>
    <% end %>

app/views/tasks/index.html.erb
<h1>ToDoアプリ</h1>
<ul>
    <%@tasks.each do |task| %>
    <li>
        <%= check_box_tag '', '', task.done, {'data-id' => task.id }%>
        <%= task.title %>
        <%= link_to '[編集]' , edit_task_path(task.id) %>
        <%= link_to '[削除]' , task_path(task.id), method: :delete, data:{confirm:'削除してもよろしいですか'} %>
    </li>
    <%end%>
    
    
</ul>

<%= link_to '新規追加', new_task_path %>

<script>
    $(function(){
        $("input[type=checkbox]").click(function(){
            $.post('/tasks/' + $(this).data('id') + '/toggle');
        });
    });
</script>

app/views/tasks/new.html.erb
<h1>新規追加画面</h1>
<%= form_for @task do |f| %>
    <p>
        <%= f.label :title %> <br>
        <%= f.text_field :title %>
        <% if @task.errors.any? %>
            <%= @task.errors.messages[:title][0] %>
        <% end %>
        
    </p>
    <p>
        <%= f.submit %>
    </p>
    <% end %>